[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python -m gunicorn app:app --workers 4 --timeout 120 --access-logfile - --error-logfile - --log-level info --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 10
healthcheckInterval = 5
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 